### ISSUE TITLE
window borders: no cursor resize arrow mode

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#43]

**Comment by mgraesslin** [comment]
Breeze theme got updated to include better fitting cursor icons. Also there is a pending review to improve KWin's handling on detecting cursor size: https://git.reviewboard.kde.org/r/121923/

**Comment by eikehein** [comment]
packages: kwin, whatever the cursors are in
fixed: Wed 14th
target ISO: Fri 16th
qa method: hover window corner with a Breeze cursor

**Comment by star-buck** [comment]
hmm, testing kci 20150116: i still see no resize cursor with Breeze deco and Breeze mouse cursor default:
one has to first select some other mouse cursor theme, apply and then switch back to breeze to actaully show resize cursors.
Should this be fixed with Kwins detection improvement and was that patch in review shipped?

**Comment by star-buck** [comment]
or is it kubuntu kci problem?

**Comment by eikehein** [comment]
I'd like Martin to comment on this since he knows best how kwin behaves now. I would add that I still don't get any resize cursors with Fedora's default cursor theme either (even though it worked fine with kwin 4).

**Comment by mgraesslin** [comment]
The patches are merged in KWin. I did not test startup, though and it's possible that there is another problem (e.g. environment variables not yet set). I will give that a try.

**Comment by mgraesslin** [comment]
on startup the environment variable XCURSOR_THEME is set while XCURSOR_SIZE isn't set. The code change I did expects both to be set.

**Comment by mgraesslin** [comment]
And (hopefully) adressed: https://git.reviewboard.kde.org/r/122139/

**Comment by mgraesslin** [comment]
package: kwin
Fixed: 21.01.
Target ISO: 23.01.

**Comment by star-buck** [comment]
seems to work
